OUTPROGS = 	\
	advance1 \
	advance2 \
	assoiter1 \
	backinserter1 \
	distance1 \
	frontinserter1 \
	inserter1 \
	istreamiter1 \
	itercategory1 \
	iterswap1 \
	ostreamiter1 \
	reviter1 \
	reviter2 \
	reviter3 \
	reviter4 \

HEADERS =	assoiter.hpp  print.hpp

include ../Makefile.h


