OUTPROGS =	\
	cat1 \
	cat2 \
	charcat1 \
	charcat2 \
	copy1 \
	copy2 \
	countlines1 \
	fstream1 \
	fstream2 \
	ignore1 \
	ignore2 \
	inbuf1 \
	io1 \
	outbuf1 \
	outbuf1i18n \
	outbuf2 \
	outbuf3 \
	sstream1 \
	sstream2 \
	streambuffer1 \
	streambuffer2 \
	streamreadwrite1 \
	streamredirect1 \
	sum1 \
	sum2 \
	timemanipulator1 \

HEADERS = frac1in.hpp   frac2in.hpp   ignore1.hpp  inbuf1.hpp   outbuf1i18n.hpp  outbuf3.hpp \
	  frac1out.hpp  frac2out.hpp  ignore2.hpp  outbuf1.hpp  outbuf2.hpp

include ../Makefile.h
