OUTPROGS =  \
	chrono1 \
	chrono2 \
	clock1 \
	enableshared1 \
	limits1 \
	minmax1 \
	pair1 \
	ratio1 \
	sharedptr1 \
	sharedptr2 \
	sharedptr3 \
	timepoint1 \
	tuple1 \
	tuple2 \
	uniqueptr1 \
	weakptr1 \
	weakptr2 \

HEADERS = clock.hpp  exception.hpp  printtuple.hpp  timepoint.hpp

include ../Makefile.h


