include ../Makefile.h

# Programme fuer die make PROG.out aufgerufen wird
#
OUTPROGS =	\
	germanbool \
	loc1 \
	loc2 \
	moneymanipulator \
	moneypunct \
	numget \
	numput \
	timeget \
	timeput \
	wbuffer \
	wstring2string \
	wstring2utf8 \

HEADERS =	wstring2string.hpp  wstring2utf8.hpp
