include ../Makefile.h

OUTPROGS = 	\
	add1 \
	algo1 \
	algo1old \
	array1 \
	assoarray1 \
	bind1 \
	copy1 \
	copy2 \
	copybug \
	deque1 \
	find1 \
	fo1 \
	foreach1 \
	foreach2 \
	forwardlist1 \
	ioiter1 \
	iterbug \
	lambda1 \
	list1 \
	list1old \
	list2 \
	multimap1 \
	multiset1 \
	prime1 \
	remove1 \
	remove2 \
	remove3 \
	remove4 \
	reviter1 \
	set1 \
	sort1 \
	sort2 \
	transform1 \
	unordmap1 \
	unordmultiset1 \
	unordmultiset2 \
	vector1 \

HEADERS =	print.hpp
