include ../Makefile.h

OUTPROGS =	\
	bind1 \
	bind2 \
	compose3 \
	fopow1 \
	foreach3 \
	lambda2 \
	lambda3 \
	lambda4 \
	lambda5 \
	lambda6 \
	removeif1 \
	sequence1 \
	sequence2 \
	sort1 \

HEADERS =	fopow.hpp  print.hpp

