OUTPROGS =	\
	array1 \
	cstylearray1 \
	cstylearray1old \
	deque1 \
	forwardlist1 \
	forwardlistfind1 \
	forwardlistsplice1 \
	hashfunc1 \
	hashfunc2 \
	list1 \
	map1 \
	map2 \
	mapcmp1 \
	mapfind1 \
	multimap1 \
	multiset1 \
	refsem1 \
	refwrap1 \
	set1 \
	setcmp1 \
	setrange1 \
	sortset \
	sortvec \
	unordinspect1 \
	unordmultimap1 \
	unordmultiset1 \
	unordset1 \
	vector1 \

CPPPROGS =	sortset sortvec

HEADERS =	buckets.hpp  findbefore.hpp  hashval.hpp  newkey.hpp  print.hpp

include ../Makefile.h
