OUTPROGS = \
            regex1          \
            regex2          \
            regex3          \
            regex4          \
            regex5          \
            regexiter1      \
            regextokeniter1

HEADERS = regexexception.hpp

include ../Makefile.h
